version: '2'

services:

  composer:
    image: composer:1.9.1
    volumes:
      - .:/app
    working_dir: /app

  apache:
    build: docker/apache
    volumes:
      - .:/var/www/html
    ports:
      - 8123:80
